### PR TITLE
Fix for #46

### PR DESCRIPTION
**Pull request by smcoll**
Updated SortedMultipleChoiceField._has_changed() to detect changes in the ordering of the data.  Proposed fix for #46.

Perhaps 'initial_set' and 'data_set' are misnomers in this case, but comparing the lists rather than sets of the lists fixed the behavior.

### CODE REVIEW

**Comment by gregmuellegger** [comment]
Hey, that's absolutely a necessary addition! Thanks for the contribution. It would be also super helpful if we had tests for this bugfix to make sure that it will never appear again. Are you up to write tests for this change? Get in touch if you want any help getting forward with this!

**Comment by smcoll** [comment]
@gregmuellegger Sure, i added a test.

Is it necessary to test for the unsorted field case (MessyStore), to make sure it *doesn't* detect a change in ordering? (that's how a regular m2m handles it)  Just thought of that.

**Comment by gregmuellegger** [comment]
Oh really cool! That was quick. The tests seem to fail for Django 1.5. Do you know what the reason might be: https://travis-ci.org/gregmuellegger/django-sortedm2m/builds/52296772

```
======================================================================

FAIL: test_form_field_detects_reordering (sortedm2m_tests.test_forms.TestSortedFormField)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/build/gregmuellegger/django-sortedm2m/sortedm2m_tests/test_forms.py", line 99, in test_form_field_detects_reordering

self.assertTrue('values' in form.changed_data)

AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by gregmuellegger** [comment]
There is a new release 0.9.4 containing your fix: https://pypi.python.org/pypi/django-sortedm2m/
Thanks for the contribution!

**Comment by smcoll** [comment]
@gregmuellegger great.  Are the tests still failing for Django 1.5? i may be able to take a look later this week.

**Comment by gregmuellegger** [comment]
@smcoll: They are good now. I fixed them :)

**Comment by smcoll** [comment]
Great, thanks.

**Pull request merged**
