### PR TITLE
Support for Django 1.11+

### PR DESCRIPTION
**Pull request by PaulGregor**
There is an issue [In Admin: build_attrs() got an unexpected keyword argument](https://github.com/gregmuellegger/django-sortedm2m/issues/107) and this PR fixes problem that causes it.

### CODE REVIEW

**Comment by nemesisdesign** [comment]
There's already a PR for this: #104

**Comment by fdintino** [comment]
Yes, and #104 also fixes deprecation warnings in 1.11.

**Comment by gregmuellegger** [comment]
Hey, thank you @PaulGregor for the contribution! I just merged #104 and released 1.4.0 including the fix. Can you please test and confirm that this also fixes your issue?

**Comment by PaulGregor** [comment]
@gregmuellegger yeap, [#104](https://github.com/gregmuellegger/django-sortedm2m/pull/104) fixes issue with 1.11 Django. Thanks.

**Pull request closed without merging**
